title: HowToGit
description: Git Cheatsheet
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-redirect-from
relative_links:
  enabled: true
  collections: true
remote_theme: pages-themes/cayman@v0.2.0
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - README.md
